idf_component_register(
    SRCS
        "main.c"
        "display_manager.c"
        "dashboard_ui.c"
        "node_state.c"
        "display_controller.c"
        "relay.c"
        "wifi_manager.c"
        "web_server.c"
        "diag_log.c"
        "ethernet_wol.c"
        "fonts/ui_font_orbitron_12.c"
        "fonts/ui_font_orbitron_16.c"
        "fonts/ui_font_orbitron_20.c"
        "fonts/ui_font_orbitron_24.c"
        "fonts/ui_font_share_tech_mono_12.c"
        "fonts/ui_font_share_tech_mono_16.c"
        "fonts/ui_font_share_tech_mono_20.c"
        "fonts/ui_font_share_tech_mono_24.c"
        "fonts/ui_font_silkscreen_12.c"
        "fonts/ui_font_silkscreen_16.c"
        "fonts/ui_font_silkscreen_20.c"
        "fonts/ui_font_silkscreen_24.c"
        "fonts/ui_font_vt323_12.c"
        "fonts/ui_font_vt323_16.c"
        "fonts/ui_font_vt323_20.c"
        "fonts/ui_font_vt323_24.c"
    INCLUDE_DIRS "." "fonts"
    REQUIRES esp_lcd lvgl esp_wifi esp_http_server driver nvs_flash microlink esp_eth
)